### ISSUE TITLE
Two or more YLGIFImageView instances animating the same YLGIFImage -> very poor performance

### ISSUE THREAD

**Issue by salling** [liyong03/YLGIFImage#11]
This scenario can happen when employing an in-memory cache for images.

**Comment by liyong03** [comment]
Do you mean they animate the same instance of YLGIFImage?

**Comment by salling** [comment]
Yes. Exactly.

**Comment by salling** [comment]
If the view could provide the frame buffer, or the different views could have their playback synchronized, the problem would be solved.
