### ISSUE TITLE
Exception when using images from URL

### ISSUE THREAD

**Issue by voronianski** [liyong03/YLGIFImage#5]
In my app such exception thrown:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _isResizable]: unrecognized selector sent to instance 0x254e068'
```

the code where I'm using the lib is as follows:

``` obj-c
NSData *imageData = [NSData dataWithContentsOfURL:[NSURL URLWithString:item.thumbnail]];
UIImage *img = [YLGIFImage imageWithData:imageData];
cell.itemThumb.image = img;
```

**Comment by CarolLee1994** [comment]
@liyong03  @voronianski I meet the same question ，i can show some gif image but not all image ，the X-code will show me     reason: '-[NSNull _isResizable]: unrecognized selector sent to instance ，would  u like tell me  the reason。

**Comment by aluco100** [comment]
@CarolLee1994 you need to set your image view to YLImageView.

Regards
